// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc862.valkyrie.subsystems;

import org.usfirst.frc862.util.DataLogger;
import org.usfirst.frc862.util.Loop;
import org.usfirst.frc862.valkyrie.Constants;
import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.RobotMap;
import org.usfirst.frc862.valkyrie.commands.*;

import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Core extends Subsystem implements Loop {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final PowerDistributionPanel powerPanel = RobotMap.corePowerPanel;
    private final Compressor compressor = RobotMap.coreCompressor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private AHRS navx = RobotMap.navx;
    private double lastTimeCompressorWasOn = 0;
    private double availableAirUnits = 0;
    private boolean previousCompressorStatus = false;
    private boolean compressorDisabled = false;
    private double compressorDisabledAt;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public Core() {
        navx.zeroYaw();

        DataLogger.addDataElement("Larkin", () -> powerPanel.getCurrent(13));
        DataLogger.addDataElement("Voltage Warning", () -> powerPanel.getVoltage());
        DataLogger.addDataElement("Current Warning", () -> powerPanel.getTotalCurrent());
        DataLogger.addDataElement("AccelX", () -> navx.getRawAccelX());
        DataLogger.addDataElement("AccelY", () -> navx.getRawAccelY());
        DataLogger.addDataElement("AccelZ", () -> navx.getRawAccelZ());
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void onStart() {
    }

    @Override
    public void onLoop() {
        boolean status = compressor.enabled();

        if (status) {
            lastTimeCompressorWasOn = Timer.getFPGATimestamp();
        } else if (this.previousCompressorStatus && compressor.getClosedLoopControl()) {
            availableAirUnits = Constants.maxAirUnits;
        }

        this.previousCompressorStatus = status;

        if (compressorDisabled
                && (Timer.getFPGATimestamp() - compressorDisabledAt) >= Constants.compressorDisabledDelay) {
            compressorDisabled = false;
        }
        compressor.setClosedLoopControl(!compressorDisabled);
    }

    @Override
    public void onStop() {
        // TODO Auto-generated method stub
    }

    public double getAvailableAirUnits() {
        return availableAirUnits;
    }

    public void useAirUnits(double val) {
        availableAirUnits -= val;
    }

    public void disableCompressor() {
        if (availableAirUnits > Constants.minimumAirReserve) {
            compressorDisabled = true;
            compressorDisabledAt = Timer.getFPGATimestamp();
        }
    }
}
