// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie.subsystems;

import java.util.function.Consumer;

import org.usfirst.frc862.valkyrie.RobotMap;
import org.usfirst.frc862.valkyrie.commands.*;
import org.usfirst.frc862.valkyrie.subsystems.modes.OpenLoopDrive;
import org.usfirst.frc862.valkyrie.subsystems.modes.SubsystemMode;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    public enum Modes {
        OPEN_LOOP, VELOCITY, BRAKE, HEADING, MOTION_PROFILE
    }    
    private Modes mode;
    OpenLoopDrive openLoopDrive = new OpenLoopDrive(this);
    SubsystemMode currentMode;

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid shifter = RobotMap.driveTrainShifter;
    private final CANTalon leftMotor1 = RobotMap.driveTrainLeftMotor1;
    private final CANTalon leftMotor2 = RobotMap.driveTrainLeftMotor2;
    private final CANTalon rightMotor1 = RobotMap.driveTrainRightMotor1;
    private final CANTalon rightMotor2 = RobotMap.driveTrainRightMotor2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void eachMotor(Consumer<CANTalon> func) {
        func.accept(leftMotor1);
        func.accept(leftMotor2);
        func.accept(rightMotor1);
        func.accept(rightMotor2);
    }
    
    public void eachPrimaryMotor(Consumer<CANTalon> func) {
        func.accept(leftMotor1);
        func.accept(rightMotor1);
    }
    
    public void eachSlaveMotor(Consumer<CANTalon> func) {
        func.accept(leftMotor2);
        func.accept(rightMotor2);
    }
    
    public void setMode(Modes m) {
        if (mode == m) return;
        
        currentMode.end();
        switch (m) {
        case OPEN_LOOP:
            currentMode = openLoopDrive;
            break;
        
        case VELOCITY:
            break;
            
        case BRAKE:
            break;
            
        case HEADING:
            break;
            
        case MOTION_PROFILE:
            break;
                        
        default:
        }
        currentMode.initialize();   
    }    
    
    public void loop() {
        currentMode.loop();
    }
    
    public double getLeftVelocity() {
        return leftMotor1.getSpeed();
    }
    
    public double getRightVelocity() {
        return rightMotor1.getSpeed();
    }
    
    public double getVelocity() {
        return (getLeftVelocity() + getRightVelocity()) / 2;
    }
    
    public double getLeftDistance() {
        return leftMotor1.getPosition();
    }
    
    public double getRightDistance() {
        return rightMotor1.getPosition();
    }
    
    public void resetDistance() {
        this.eachPrimaryMotor((CANTalon t) -> {
           t.setPosition(0);
           t.setEncPosition(0); 
        });
    }
}

