
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc862.trajectory.RobotState;
import org.usfirst.frc862.util.Logger;
import org.usfirst.frc862.valkyrie.Constants;
import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.RobotMap;
import org.usfirst.frc862.valkyrie.subsystems.DriveTrain;
import org.usfirst.frc862.vision.TargetInfo;

import com.team254.lib.util.ChezyMath;

/**
 *
 */
public class AlignToPeg extends Command {
    boolean waiting_for_vision;
    private double start_time;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_degrees;
    private double goal;
    private double error;
    private float previousHeading;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AlignToPeg() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        super(0);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    public void setDesiredChange(double delta) {
        m_degrees = delta;
        updateSetPoint();
    }
    
    protected void updateSetPoint() {
        previousHeading = RobotMap.navx.getFusedHeading();
        Robot.driveTrain.setMode(DriveTrain.Modes.VELOCITY);
        goal = ChezyMath.boundAngleNeg180to180Degrees(previousHeading + m_degrees);        
        error = m_degrees;
    }    

    // Called just before this Command runs the first time
    protected void initialize() {
        waiting_for_vision = true;
        start_time = Timer.getFPGATimestamp();
    }

    protected void execute() {
        if (waiting_for_vision) {
            Logger.debug("Waiting for vision");
            TargetInfo peg = RobotState.getInstance().getCurrentVisionTarget();
            if (peg != null & peg.getCaptureTime() > start_time) {
                setDesiredChange(peg.getTheta());
                Logger.debug("  we have vision: " + m_degrees + " // " + error);
                waiting_for_vision = false;
            }
        } else {
            double heading = RobotMap.navx.getFusedHeading();
            error = ChezyMath.boundAngleNeg180to180Degrees(goal - heading);
            Logger.debug("  rotating: " + goal + " // " + heading + " // " + error);
            double rotatePGain = Robot.shifter.getMaxVelocity() / 180.0 * 3.9;
            double power = rotatePGain * error;
            
            if(Math.abs(power) < Constants.MinRotatePower){
                power = Constants.MinRotatePower * ((power > 0) ? 1 : -1);
            }
            SmartDashboard.putNumber("Rotate Power", power);
            Robot.driveTrain.set(power, -power);
            SmartDashboard.putNumber("Error", error);
            SmartDashboard.putNumber("Power", power);
        }
    }
    
    protected boolean isFinished() {
        Logger.debug("  isFinished: " + error);
        return !waiting_for_vision && 
                Math.abs(error) < Constants.rotateEpsilon;
    }
    
    // Called once after isFinished returns true
    protected void end() {
        Robot.driveTrain.stop();
        Logger.debug("rotated!");
        Logger.flush();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
