// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie.commands;
import org.usfirst.frc862.valkyrie.Constants;
import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.subsystems.DriveTrain.Modes;

import com.team254.lib.util.ChezyMath;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class ArcadeDrive extends Command {
    boolean isStraight = false;
    double originalGyroValue = 0.0;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ArcadeDrive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.driveTrain.setMode(Modes.VELOCITY);
        isStraight = false;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if (Math.abs(Robot.oi.driverRight.getRawAxis(0)) < Constants.deadband && !isStraight) {
            isStraight = true;
            originalGyroValue = Robot.driveTrain.getGyroAngle();
        } else if (Math.abs(Robot.oi.driverRight.getRawAxis(0)) > 0.1 && isStraight) {
            isStraight = false;
            Robot.driveTrain.setStraightAdjust(0);
        }
        
        if (isStraight) {
            double angleDiff = ChezyMath.getDifferenceInAngleDegrees(originalGyroValue, Robot.driveTrain.getGyroAngle());
            Robot.driveTrain.setStraightAdjust(angleDiff * Constants.ArcadeAngleP);
        }
        Robot.driveTrain.teleopArcade(
                Robot.oi.driverLeft.getRawAxis(1), 
                Robot.oi.driverRight.getRawAxis(0));
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
