// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc862.valkyrie.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc862.valkyrie.Constants;
import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.RobotMap;

/**
 *
 */
public class Autoshifter extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    private Timer lowGearUpshiftTimer;
    private Timer highGearDownshiftTimer;
    private Timer lastShiftTimer;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Autoshifter() {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shifter);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        lowGearUpshiftTimer = new Timer();
        highGearDownshiftTimer = new Timer();
        lastShiftTimer = new Timer();
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        lowGearUpshiftTimer.start();
        lowGearUpshiftTimer.reset();
        highGearDownshiftTimer.start();
        highGearDownshiftTimer.reset();
        lastShiftTimer.start();
        lastShiftTimer.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if (Robot.shifter.isLowGear()) {
            if (lastShiftTimer.hasPeriodPassed(Constants.shiftHysteresis)) {
                if (Robot.driveTrain.getAbsVelocity() > Constants.MinUpshiftVelocity) {
                    if (lowGearUpshiftTimer.hasPeriodPassed(Constants.VelocityUpshiftTime)) {
                        Robot.shifter.upShift();
                        highGearDownshiftTimer.reset();
                        lastShiftTimer.reset();
                    }
                } else {
                    lowGearUpshiftTimer.reset();
                }
            } else {
                if (RobotMap.navx.getRawAccelY() < Constants.CrashDeacceleration) {
                    Robot.shifter.downShift();
                } else if (Robot.driveTrain.getAbsVelocity() < Constants.CoastVelocity) {
                    if (highGearDownshiftTimer.hasPeriodPassed(Constants.CoastTriggerTime)) {
                        Robot.shifter.downShift();
                        lowGearUpshiftTimer.reset();
                        lastShiftTimer.reset();
                        // blorp glorp
                    }
                } else {
                    highGearDownshiftTimer.reset();
                }
            }
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
        lowGearUpshiftTimer.stop();
        highGearDownshiftTimer.stop();
        lastShiftTimer.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
