// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie.commands;
import org.usfirst.frc862.valkyrie.Constants;
import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.subsystems.GearCollector.State;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class AutoRetractGearDoor extends Command {
    enum CmdState { Closed, Opened, Reversing, Moving, Closing };
    CmdState state = CmdState.Closed;
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutoRetractGearDoor() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.gearCollector);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        if (Robot.gearCollector.getEjectDoorState() == State.EXTENDED) {
            state = CmdState.Opened;
        } else {
            state = CmdState.Closed;
        }
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        switch (state) {
        case Closed:
            // do nothing here
            break;
        case Closing:
            Robot.gearCollector.closeGearEjectDoor();
            Robot.gearCollector.extend();
            state = CmdState.Closed;
            break;
        case Moving:
            if (Robot.driveTrain.getVelocity() > Constants.notACrawl) {
                state = CmdState.Closing;
            }
            break;
        case Opened:
            // Wait until we reverse at least a little
            if (Robot.driveTrain.getVelocity() < 0) {
                state = CmdState.Reversing;
            }
            break;
        case Reversing:
            if (Robot.driveTrain.getVelocity() < 0) {
                // Now wait until we start to move forward
                state = CmdState.Moving;
            }            
            break;
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
