// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc862.valkyrie.commands;

import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.RobotMap;
import org.usfirst.frc862.valkyrie.subsystems.DriveTrain.Modes;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */

public class DriveTrainTest extends Command {
    private enum State {
        RightMotor1, RightMotor2, RightMotor3, LeftMotor1, LeftMotor2, LeftMotor3, WinchMotor1, WinchMotor2,
        GearCollectorExtend,GearCollectorRetract, DriveTrainUpshift, DriveTrainDownshift
    }

    private State state;
    private boolean ispressed = false;
    private boolean isFinished = false;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveTrainTest() {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.driveTrain.setMode(Modes.TEST);
        Timer timer = new Timer();
        timer.start();
        state = State.RightMotor1;
        isFinished = false;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {

        switch (state) {
        case RightMotor1:
            rightMotor1();
            break;
        case RightMotor2:
            rightMotor2();
            break;
        case RightMotor3:
            rightMotor3();
            break;
        case LeftMotor1:
            leftMotor1();
            break;
        case LeftMotor2:
            leftMotor2();
            break;
        case LeftMotor3:
            leftMotor3();
            break;
        case WinchMotor1:
            winchMotor1();
            break;
        case WinchMotor2:
            winchMotor2();
            break;
        case GearCollectorExtend:
            gearCollectorExtend();
            break;
        case GearCollectorRetract:
            gearCollectorRetract();
            break;
        case DriveTrainUpshift:
            driveTrainUpshift();
            break;
        case DriveTrainDownshift:
            driveTrainDownshift();
            break;
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isFinished;
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.driveTrain.setMode(Modes.VELOCITY);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }

    boolean buttonRealeased() {
        if (ispressed && !Robot.oi.buttonThing.getRawButton(0)) {
            ispressed = false;
            return true;
        } else if (Robot.oi.buttonThing.getRawButton(0)) {
            ispressed = true;
        }
        return false;
    }

    private void rightMotor1() {
        RobotMap.driveTrainRightMotor1.set(0.5);

        if (buttonRealeased()) {
            RobotMap.driveTrainRightMotor1.set(0);
            state = State.RightMotor2;
        }
    }

    private void rightMotor2() {
        RobotMap.driveTrainRightMotor2.set(0.5);

        if (buttonRealeased()) {
            RobotMap.driveTrainRightMotor2.set(0);
            state = State.RightMotor3;
        }
    }

    private void rightMotor3() {
        RobotMap.driveTrainRightMotor3.set(0.5);

        if (buttonRealeased()) {
            RobotMap.driveTrainRightMotor3.set(0);
            state = State.LeftMotor1;
        }
    }

    private void leftMotor1() {
        RobotMap.driveTrainLeftMotor1.set(0.5);

        if (buttonRealeased()) {
            RobotMap.driveTrainLeftMotor1.set(0);            
            state = State.LeftMotor2;
        }
    }

    private void leftMotor2() {
        RobotMap.driveTrainLeftMotor2.set(0.5);

        if (buttonRealeased()) {
            RobotMap.driveTrainLeftMotor2.set(0);
            state = State.LeftMotor3;
        }
    }

    private void leftMotor3() {
        RobotMap.driveTrainLeftMotor3.set(0.5);

        if (buttonRealeased()) {
            RobotMap.driveTrainLeftMotor3.set(0);
            state = State.WinchMotor1;
        }
    }

    private void winchMotor1() {
        RobotMap.winchWinchMotor1.set(0.5);

        if (buttonRealeased()) {
            state = State.WinchMotor2;
        }
    }

    private void winchMotor2() {
        RobotMap.winchWinchMotor2.set(0.5);

        if (buttonRealeased()) {
            state = State.GearCollectorExtend;
        }
    }

    private void gearCollectorExtend() {
        Robot.gearCollector.extend();

        if (buttonRealeased()) {
            state = State.GearCollectorRetract;
        }
    }

    private void gearCollectorRetract() {
        Robot.gearCollector.retract();

        if (buttonRealeased()) {
            state = State.DriveTrainUpshift;
        }
    }

    private void driveTrainUpshift() {
        Robot.shifter.upShift();

        if (buttonRealeased()) {
            state = State.DriveTrainDownshift;
        }
    }

    private void driveTrainDownshift() {
        Robot.shifter.downShift();

        if (buttonRealeased()) {
            isFinished = true;
        }
    }
}
