// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie.commands;
import org.usfirst.frc862.util.LightningMath;
import org.usfirst.frc862.valkyrie.Constants;
import org.usfirst.frc862.valkyrie.Robot;

import com.team254.lib.trajectory.PathGenerator;
import com.team254.lib.trajectory.Trajectory;
import com.team254.lib.trajectory.Trajectory.Pair;
import com.team254.lib.trajectory.Trajectory.Segment;
import com.team254.lib.trajectory.TrajectoryGenerator;
import com.team254.lib.trajectory.WaypointSequence;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class DynamicCheese extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    private Trajectory trajectory;
    private int segment_index;
    private Pair path;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DynamicCheese() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        WaypointSequence points = new WaypointSequence(10);
        points.addWaypoint(new WaypointSequence.Waypoint(0,0,0));
//        points.addWaypoint(new WaypointSequence.Waypoint(6.5,-3,-Math.PI / 3));
        points.addWaypoint(new WaypointSequence.Waypoint(7,-2.67,-Math.PI / 3));
//        points.addWaypoint(new WaypointSequence.Waypoint(7.1,-2.67,-Math.PI / 3));
        
        TrajectoryGenerator.Config config = new TrajectoryGenerator.Config();
        config.dt = 0.02;
        config.max_acc = 8 / 3;
        config.max_jerk = 50 / 2;
        config.max_vel = 3.5;
        trajectory = PathGenerator.generateFromPath(points, config);
        path = PathGenerator.makeLeftAndRightTrajectories(trajectory, Constants.wheelBase);
        segment_index = 0;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Segment l = path.left.getSegment(segment_index);
        Segment r = path.right.getSegment(segment_index);
        segment_index += 1;
        
        Robot.driveTrain.set(LightningMath.fps2rpm(l.vel), LightningMath.fps2rpm(r.vel));
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return segment_index >= trajectory.getNumSegments();
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
