// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc862.valkyrie.commands;

import edu.wpi.first.wpilibj.command.ConditionalCommand;

import org.usfirst.frc862.util.Logger;
import org.usfirst.frc862.valkyrie.Robot;

/**
 *
 */
public class pegTester extends ConditionalCommand {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public pegTester() {
        super(new DoNothing(), new RetryPeg());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // addSequential(new ToggleGearEject());
    }

    protected boolean condition() {
        DriveBackwardDistance.setDistance(-2.4);
        boolean status = Robot.gearDetector.pegPresent();
        Logger.debug("pegTester: " + status);
        return status;
    }
}
