// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie.commands;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import org.usfirst.frc862.util.Logger;
import org.usfirst.frc862.util.RecordedPath;
import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.subsystems.DriveTrain;

import com.team254.lib.trajectory.Path;
import com.team254.lib.trajectory.Trajectory;
import com.team254.lib.trajectory.io.TextFileSerializer;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class RecordManualMotion extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private String m_path_name;
    private RecordedPath path;
    private DriveTrain drive;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public RecordManualMotion(String path_name) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_path_name = path_name;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.shifter.upShift();
        path = new RecordedPath();
        drive = Robot.driveTrain;
        drive.configure_test_mode();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        path.add(drive.getLeftDistance(),
                drive.getRightDistance(), 
                drive.getGyroAngle(),
                Timer.getFPGATimestamp());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    protected String getFileName() {
        return "/home/lvuser/" + m_path_name + ".txt";
    }
    
    // Called once after isFinished returns true
    protected void end() {
        // convert to 254 trajectory
        Trajectory.Pair pair = path.convertTrajectory();
        
        // write to file
        TextFileSerializer js = new TextFileSerializer();
        String serialized = js.serialize(new Path(m_path_name, pair));
        //System.out.print(serialized);
        String fullpath = getFileName();
        if (!writeFile(fullpath, serialized)) {
          Logger.debug(fullpath + " could not be written!!!!");
        } else {
          Logger.debug("Wrote " + fullpath);
        }    

        // put things back to normal
        drive.configure_follow_modes();
    }

    private static boolean writeFile(String path, String data) {
        try {
            Logger.debug("Writing path file to: " + path);
            File file = new File(path);

            if (!file.exists()) {
                file.createNewFile();
            }

            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException e) {
            Logger.error(e.toString());
            return false;
        }

        return true;
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
