// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie.commands;
import org.usfirst.frc862.util.LightningMath;
import org.usfirst.frc862.util.Logger;
import org.usfirst.frc862.util.StatefulCommand;
import org.usfirst.frc862.valkyrie.Constants;
import org.usfirst.frc862.valkyrie.Robot;
import org.usfirst.frc862.valkyrie.RobotMap;

import com.team254.lib.util.ChezyMath;

import edu.wpi.first.wpilibj.Timer;

/**
 *
 */
public class SpinLeft extends StatefulCommand {
    enum States {
        SETUP, SLOW_DOWN, ROLL_BACK_RIGHT, ROLL_FORWARD_LEFT, STRAIGHTEN, DONE
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    private double start_angle;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public SpinLeft() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        super(States.ROLL_BACK_RIGHT);
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shifter);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        start_angle = ChezyMath.boundAngleNeg180to180Degrees(Robot.driveTrain.getGyroAngle());
        // Robot.shifter.upShift();
        setState(States.ROLL_BACK_RIGHT);
    }

    public void setup() {
        setState(States.SLOW_DOWN);
    }
    
    public void slowDown() {
        if (Robot.driveTrain.getVelocity() < Constants.MinSpinSpeed) {
            setState(States.ROLL_BACK_RIGHT);            
        }
        Robot.driveTrain.set(0, 0);
    }
    
    public void rollBackRight() {
        Robot.driveTrain.teleop(-0.2, 1.0);
        Logger.debug("rollbackRight: " + error());
        if (error() < -45) {
            Robot.shifter.upShift();
        }
        if (error() < -170 || error() > 90) {
            this.setState(States.ROLL_FORWARD_LEFT);
        }
    }
    
    public void rollForwardLeft() {
        Robot.driveTrain.teleop(-1.0, 0.2);
        Logger.debug("rollForwardLeft: " + error());
        if (Math.abs(error()) < 60) {
            this.setState(States.STRAIGHTEN);            
        }
    }
    
    public void straighten() {
        double rotatePGain = (Constants.maxVelocityHigh / 90.0) * error();
        double power = Constants.maxVelocityHigh;

        Robot.driveTrain.set(power + rotatePGain, power - rotatePGain);
    }
    
    public double error() {
        double heading = Robot.driveTrain.getGyroAngle();
        return ChezyMath.boundAngleNeg180to180Degrees(start_angle - heading);        
    }
    
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.driveTrain.teleop(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
