// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie;

import org.usfirst.frc862.util.FaultCode;
import org.usfirst.frc862.util.FaultCommand;
import org.usfirst.frc862.valkyrie.commands.ArcadeDrive;
import org.usfirst.frc862.valkyrie.commands.AutonBlueBoiler;
import org.usfirst.frc862.valkyrie.commands.AutonBlueFeeder;
import org.usfirst.frc862.valkyrie.commands.AutonRedBoiler;
import org.usfirst.frc862.valkyrie.commands.AutonRedFeeder;
import org.usfirst.frc862.valkyrie.commands.Autoshifter;
import org.usfirst.frc862.valkyrie.commands.CalibratedClimb;
import org.usfirst.frc862.valkyrie.commands.Climb;
import org.usfirst.frc862.valkyrie.commands.ClimbOverride;
import org.usfirst.frc862.valkyrie.commands.DoNothing;
import org.usfirst.frc862.valkyrie.commands.DownShift;
import org.usfirst.frc862.valkyrie.commands.DriveStraight;
import org.usfirst.frc862.valkyrie.commands.AutonStraight;
import org.usfirst.frc862.valkyrie.commands.DriveTrainTest;
import org.usfirst.frc862.valkyrie.commands.DynamicCheese;
import org.usfirst.frc862.valkyrie.commands.DynamicExtraCheese;
import org.usfirst.frc862.valkyrie.commands.ExtendGearCollector;
import org.usfirst.frc862.valkyrie.commands.FindSticktion;
import org.usfirst.frc862.valkyrie.commands.FollowMotionProfile;
import org.usfirst.frc862.valkyrie.commands.GetDataPacket;
import org.usfirst.frc862.valkyrie.commands.HighCurrentResponse;
import org.usfirst.frc862.valkyrie.commands.LeftDynamicProfile;
import org.usfirst.frc862.valkyrie.commands.ManualShifter;
import org.usfirst.frc862.valkyrie.commands.OpenLoopDriveCommand;
import org.usfirst.frc862.valkyrie.commands.PauseCompressor;
import org.usfirst.frc862.valkyrie.commands.ResetDataLogger;
import org.usfirst.frc862.valkyrie.commands.RetractGearCollector;
import org.usfirst.frc862.valkyrie.commands.RightDynamicProfile;
import org.usfirst.frc862.valkyrie.commands.Rotate;
import org.usfirst.frc862.valkyrie.commands.SystemTest;
import org.usfirst.frc862.valkyrie.commands.ToggleGearCollector;
import org.usfirst.frc862.valkyrie.commands.TurnOffMotors;
import org.usfirst.frc862.valkyrie.commands.TurnOnLEDRing;
import org.usfirst.frc862.valkyrie.commands.Upshift;
import org.usfirst.frc862.valkyrie.commands.VisionFeedStation;
import org.usfirst.frc862.valkyrie.commands.VisionGear;
import org.usfirst.frc862.valkyrie.commands.WallFollow;
import org.usfirst.frc862.valkyrie.commands.WriteConstants;
import org.usfirst.frc862.valkyrie.triggers.HighCurrentTrigger;
import org.usfirst.frc862.valkyrie.triggers.LowVoltageTrigger;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton shiftSelectAuto;
    public JoystickButton shiftSelectManual;
    public Joystick buttonThing;
    public JoystickButton winchButton;
    public JoystickButton extendGearButton;
    public JoystickButton retractGearButton;
    public Joystick driverLeft;
    public JoystickButton winchButton2;
    public Joystick driverRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        driverRight = new Joystick(1);
        
        winchButton2 = new JoystickButton(driverRight, 7);
        winchButton2.whileHeld(new ClimbOverride());
        driverLeft = new Joystick(0);
        
        retractGearButton = new JoystickButton(driverLeft, 10);
        retractGearButton.whileHeld(new RetractGearCollector());
        extendGearButton = new JoystickButton(driverLeft, 9);
        extendGearButton.whileHeld(new ExtendGearCollector());
        winchButton = new JoystickButton(driverLeft, 2);
        winchButton.whileHeld(new CalibratedClimb());
        buttonThing = new Joystick(3);
        
        shiftSelectManual = new JoystickButton(buttonThing, 1);
        shiftSelectManual.whenPressed(new ManualShifter());
        shiftSelectAuto = new JoystickButton(buttonThing, 1);
        shiftSelectAuto.whenReleased(new Autoshifter());

        // SmartDashboard Buttons
        SmartDashboard.putData("AutonBlueBoiler", new AutonBlueBoiler());
        SmartDashboard.putData("AutonBlueFeeder", new AutonBlueFeeder());
        SmartDashboard.putData("AutonRedBoiler", new AutonRedBoiler());
        SmartDashboard.putData("AutonRedFeeder", new AutonRedFeeder());
        SmartDashboard.putData("AutonStraight", new AutonStraight());
        SmartDashboard.putData("Do Nothing", new DoNothing());
        SmartDashboard.putData("Upshift", new Upshift());
        SmartDashboard.putData("DownShift", new DownShift());
        SmartDashboard.putData("WriteConstants", new WriteConstants());
        SmartDashboard.putData("Follow Motion Profile", new FollowMotionProfile());
        SmartDashboard.putData("Climb", new Climb());
        SmartDashboard.putData("CalibratedClimb", new CalibratedClimb());
        SmartDashboard.putData("PauseCompressor", new PauseCompressor());
        SmartDashboard.putData("Rotate: left", new Rotate(-90));
        SmartDashboard.putData("Rotate: right", new Rotate(90));
        SmartDashboard.putData("Rotate: reverse", new Rotate(180));
        SmartDashboard.putData("Rotate: SmallLeft", new Rotate(-30));
        SmartDashboard.putData("DriveStraight", new DriveStraight());
        SmartDashboard.putData("Get Data Packet", new GetDataPacket());
        SmartDashboard.putData("Open Loop Drive Command", new OpenLoopDriveCommand());
        SmartDashboard.putData("Arcade Drive", new ArcadeDrive());
        SmartDashboard.putData("DynamicCheese", new DynamicCheese());
        SmartDashboard.putData("ResetDataLogger", new ResetDataLogger());
        SmartDashboard.putData("DynamicExtraCheese", new DynamicExtraCheese());
        SmartDashboard.putData("HighCurrentResponse", new HighCurrentResponse());
        SmartDashboard.putData("TurnOffMotors: OneSecond", new TurnOffMotors(1));
        SmartDashboard.putData("Autoshifter", new Autoshifter());
        SmartDashboard.putData("VisionFeedStation", new VisionFeedStation());
        SmartDashboard.putData("VisionGear", new VisionGear());
        SmartDashboard.putData("WallFollow", new WallFollow());
        SmartDashboard.putData("Extend Gear Collector", new ExtendGearCollector());
        SmartDashboard.putData("Retract Gear Collector", new RetractGearCollector());
        SmartDashboard.putData("Toggle Gear Collector", new ToggleGearCollector());
        SmartDashboard.putData("DriveTrainTest", new DriveTrainTest());
        SmartDashboard.putData("Find Sticktion", new FindSticktion());
        SmartDashboard.putData("Climb Override", new ClimbOverride());
        SmartDashboard.putData("TurnOnLEDRing", new TurnOnLEDRing());
        SmartDashboard.putData("ManualShifter", new ManualShifter());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        SmartDashboard.putData("Auton Blue Boiler", new AutonBlueBoiler());
        SmartDashboard.putData("Auton Blue Feeder", new AutonBlueFeeder());
        SmartDashboard.putData("Auton Red Boiler", new AutonRedBoiler());
        SmartDashboard.putData("Auton Red Feeder", new AutonRedFeeder());
        SmartDashboard.putData("Auton Straight", new AutonStraight());

        SmartDashboard.putData("SystemTest", new SystemTest());
        SmartDashboard.putData("Left Dynamic", new LeftDynamicProfile());
        SmartDashboard.putData("Right Dynamic", new RightDynamicProfile());

        // Todo integrate either/two button commands into robotbuilder
        // new EitherButtonTrigger(cmdUpshift1, cmdUpShift2).whenActive(new Upshift());

        new LowVoltageTrigger(RobotMap.corePowerPanel, Constants.LowVoltage, Constants.LVTriggerTime).whenActive(
                new FaultCommand(FaultCode.Codes.LOW_MAIN_VOLTAGE)
        );

        new HighCurrentTrigger(RobotMap.corePowerPanel, Constants.HighCurrentThreshold, Constants.HCTriggerTime).whenActive(
                new HighCurrentResponse()
        );
        
        new HighCurrentTrigger(RobotMap.corePowerPanel, Constants.HighCurrentThreshold, Constants.HCScaryTriggerTime).whenActive(
                new TurnOffMotors(Constants.MotorOffTime)
        );

        // TODO duration may be too long, test test test
//        new CrashTrigger(RobotMap.navx, Constants.CrashDeacceleration, Constants.CrashDuration).whenActive(
//                new DownShift()
//        );
//
//// Relying current right now, open to better implementations
////        new LosingPushingBattleTrigger(Robot.driveTrain, Constants.LostBattleTriggerTime).whenActive(
////                new DownShift()
////        );
//
//        new CoastTrigger(Robot.driveTrain, Constants.CoastVelocity,
//                Constants.CoastTriggerTime, Constants.MaxCoastPower).whenActive(
//                new DownShift()
//        );
//
//        //Luke shook Nicole
//        new VelocityTalonUpshiftTrigger(Robot.driveTrain, Constants.MinRequestedPowerForUpshift,
//                Constants.MinUpshiftVelocity, Constants.VelocityUpshiftTime).whenActive(
//                new Upshift()
//        );
        
        /*
        new EncoderFailure(RobotMap.corePowerPanel, Constants.HighCurrentThreshold, Constants.TriggerTime).whenActive(
                new LogCommand(() -> "Current warning: " + RobotMap.corePowerPanel.getTotalCurrent())
        );
        */
//        if (VelocityTalonUpshiftTrigger.this.get()) //how does this work I don't get it
//            Robot.driveTrain.upShift();
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getButtonThing() {
        return buttonThing;
    }

    public Joystick getDriverLeft() {
        return driverLeft;
    }

    public Joystick getDriverRight() {
        return driverRight;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

