// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.valkyrie;

import com.kauailabs.navx.frc.AHRS;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.SPI;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainStubLeftMotor1;
    public static CANTalon driveTrainStubLeftMotor2;
    public static CANTalon driveTrainStubRightMotor1;
    public static CANTalon driveTrainStubRightMotor2;
    public static PowerDistributionPanel driveTrainStubPowerDistributionPanel;
    public static DoubleSolenoid driveTrainStubShifter;
    public static Compressor driveTrainStubCompressor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static AHRS navx;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainStubLeftMotor1 = new CANTalon(3);
        LiveWindow.addActuator("DriveTrainStub", "Left Motor 1", driveTrainStubLeftMotor1);
        
        driveTrainStubLeftMotor2 = new CANTalon(4);
        LiveWindow.addActuator("DriveTrainStub", "Left Motor 2", driveTrainStubLeftMotor2);
        
        driveTrainStubRightMotor1 = new CANTalon(5);
        LiveWindow.addActuator("DriveTrainStub", "Right Motor 1", driveTrainStubRightMotor1);
        
        driveTrainStubRightMotor2 = new CANTalon(6);
        LiveWindow.addActuator("DriveTrainStub", "Right Motor 2", driveTrainStubRightMotor2);
        
        driveTrainStubPowerDistributionPanel = new PowerDistributionPanel(1);
        LiveWindow.addSensor("DriveTrainStub", "PowerDistributionPanel", driveTrainStubPowerDistributionPanel);
        
        driveTrainStubShifter = new DoubleSolenoid(2, 0, 1);
        LiveWindow.addActuator("DriveTrainStub", "Shifter", driveTrainStubShifter);
        
        driveTrainStubCompressor = new Compressor(2);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        navx = new AHRS(SPI.Port.kMXP);
//        navx = new AHRS(I2C.Port.kMXP);
    }
}
